#! /bin/bash
#
# chkconfig: 2345 10 90
# description: Activates/Deactivates all network interfaces configured to \
#              start at boot time.
#
### BEGIN INIT INFO
### END INIT INFO

# Source function library.
. /etc/init.d/functions

CWD=$(pwd)

rc=0

REDIS_BIN=/usr/local/bin/redis-server

REDIS_CONFIG=/etc/redis.conf

REDIS_PID_FILE=/var/run/redis_6379.pid

function chck_port()
{
    netstat -lpn | grep -w 6379 | grep -v grep | wc -l
}

# See how we were called.
case "$1" in
  start)
	[ "$EUID" != "0" ] && exit 4
 
    $REDIS_BIN $REDIS_CONFIG &

    sleep 1

    cnt=$(chck_port)
    if [ $cnt -eq 0 ]; then
        echo "Start redis failed."
        exit 5
    fi
    ;;

  stop)
	[ "$EUID" != "0" ] && exit 4
    kill -9 $(cat $REDIS_PID_FILE)
    ;;

  status)
      cnt=$(chck_port)
      if [ $cnt -eq 1 ] ; then
          echo "Redis is running."
      elif [ $cnt -eq 0 ]; then
          echo "Redis is not running"
      fi
	;;

  reload|force-reload)
    echo "" 
    ;;

  restart)
    cd "$CWD"
	$0 stop
	$0 start
	rc=$?
	;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|reload|force-reload}"
        exit 2
esac

exit $rc
